name: Simple Conda Run

on: [push]

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-activate-base: true

      - name: Run main.py
        run: python main.py
